### ISSUE TITLE
Enchantment books bought from wandering trader not usable

### ISSUE THREAD

**Issue by DLumina** [Block-Vader/wandering_trader_improvements#4]
Version: 1.16.3-1.1.0.0 (newest)

Description: the nbt tag for the book is wrong. Instead of "Enchantments", use "StoredEnchantments" could make them usable on anvil. To distinguish: enchantment books with "StoredEnchantments" would have its name yellow, while with "Enchantments" its name would be blue.

**Comment by Block-Vader** [comment]
Fixed in commit bbea2ad252e32445fbf2a0c38367b7e7c88d2fd8.
